public enum EMenuCourse
{
    NONE = 0,
    TERMOTANQUES_Y_PISCINAS = 1,
    PANELES_FOTOVOLTAICOS = 2,
    ENERGIA_EOLICA = 3,
    HIGIENE_Y_SEGURIDAD_LABORAL = 4,
    HUELLA_CARBONO = 5,
    AUDITORIA_ISO = 6,
    COMPOSTERAS = 7,
    HUERTAS = 8,
    CULTIVOS = 9,
    MARCA_SUSTENTABLE = 10,
    MATERIALES_SOSTENIBLES = 11,
    TINTE_TELA = 12,
}